### ISSUE TITLE
formatHttpRequest sets url.path incorrectly

### ISSUE THREAD

**Issue by tamias** [elastic/ecs-logging-js#15]
According to the ECS guide, url.path should be:
> Path of the request, such as "/search".

However, `formatHttpRequest` sets url.path to the full url excluding the query and/or anchor:

```
  var hasQuery = url.indexOf('?')
  var hasAnchor = url.indexOf('#')
  if (hasQuery > -1 && hasAnchor > -1) {
    ecs.url.path = url.slice(0, hasQuery)
    ecs.url.query = url.slice(hasQuery + 1, hasAnchor)
    ecs.url.fragment = url.slice(hasAnchor + 1)
  } else if (hasQuery > -1) {
    ecs.url.path = url.slice(0, hasQuery)
    ecs.url.query = url.slice(hasQuery + 1)
  } else if (hasAnchor > -1) {
    ecs.url.path = url.slice(0, hasAnchor)
    ecs.url.fragment = url.slice(hasAnchor + 1)
  } else {
    ecs.url.path = url
  }
```

e.g. for the url "http://www.example.com/index.html?foo=bar", url.path will be set to "http://www.example.com/index.html", but it should be set to "/index.html".

**Comment by tamias** [comment]
I suppose this is because the url in the request object will not include the protocol and hostname in the first place...  If that's the case then this issue should just be closed.

**Comment by delvedor** [comment]
Hello! You are right, this issue is happening because the `request.url` do not give us the full URL, but only the path + query and anchor.
For building the full URL we should combine the `request.headers.host` as well.
I'll work on a fix for this :)

**Comment by delvedor** [comment]
I've opened https://github.com/elastic/ecs-logging-js/pull/16 which should fix your issue as well, please take a look :)
